FROM openjdk:8-jre
LABEL maintainer="melvyn.herzig@heig-vd.ch"
  
COPY MockMock-1.4.0.one-jar.jar /opt/app/MockMock-1.4.0.one-jar.jar

CMD ["java","-jar","/opt/app/MockMock-1.4.0.one-jar.jar","-p","25"]
